#!/usr/bin/env bash
# Tier 3 substitutions for mqube-company-service — generated by bin/analyze-repo.sh.
# Review every line; the analyzer is best-effort, not authoritative.

# Skip private OCI chart dep(s); sync only the consumer's own release.
# shellcheck disable=SC2034  # PSL_SELECTOR is read by preview-up.sh after sourcing.
PSL_SELECTOR="name=preview"

psl_pre() {
  local ns="$1"
  $K -n "$ns" create secret generic backend-service-oauth --from-literal=BASE_URL=stub --from-literal=CLIENT_ID=stub --from-literal=CLIENT_SECRET=stub --dry-run=client -o yaml | $K apply -f - >/dev/null
  $K -n "$ns" create secret generic company-house --from-literal=auth-token=stub --dry-run=client -o yaml | $K apply -f - >/dev/null
  $K -n "$ns" create secret generic credit-safe-user --from-literal=baseAddress.txt=stub --from-literal=password.txt=stub --from-literal=username.txt=stub --dry-run=client -o yaml | $K apply -f - >/dev/null
  $K -n "$ns" create secret generic db-connection --from-literal=dbConnection.txt=stub --dry-run=client -o yaml | $K apply -f - >/dev/null
  $K -n "$ns" create secret generic environment --from-literal=environment.txt=stub --dry-run=client -o yaml | $K apply -f - >/dev/null
  $K -n "$ns" create secret generic experian-company --from-literal=ClientId=stub --from-literal=ClientSecret=stub --from-literal=Password=stub --from-literal=Url=stub --from-literal=UserName=stub --dry-run=client -o yaml | $K apply -f - >/dev/null
  $K -n "$ns" create secret generic proxy-company --from-literal=host=stub --from-literal=password=stub --from-literal=user=stub --dry-run=client -o yaml | $K apply -f - >/dev/null
  $K -n "$ns" create secret generic redis --from-literal=redis.txt=stub --dry-run=client -o yaml | $K apply -f - >/dev/null
  $K -n "$ns" create secret generic rmq-rabbitmq-ha --from-literal=rabbitmq-hostname=stub --from-literal=rabbitmq-password=stub --from-literal=rabbitmq-username=stub --dry-run=client -o yaml | $K apply -f - >/dev/null
}

